ITEM_ADDING_ERROR_CODE = 1000
ITEM_ADDING_ERROR_TEXT = "Failed to add product."
ITEM_REMOVING_ERROR_CODE = 1001
ITEM_REMOVING_ERROR_TEXT = "Item does not exist in the cart."
CART_RETRIEVE_ERROR_CODE = 2000
CART_RETRIEVE_ERROR_TEXT = "Cart not found."

ITEM_ADDING_ERROR = {"code": ITEM_ADDING_ERROR_CODE, "message": ITEM_ADDING_ERROR_TEXT}
ITEM_REMOVING_ERROR = {"code": ITEM_REMOVING_ERROR_CODE, "message": ITEM_REMOVING_ERROR_TEXT}
CART_RETRIEVE_ERROR = {"code": CART_RETRIEVE_ERROR_CODE, "message": CART_RETRIEVE_ERROR_TEXT}
