ACTIVE_CART_ALREADY_EXISTS_ERROR_CODE = 1000
ACTIVE_CART_ALREADY_EXISTS_ERROR_TEXT = "Active cart already exists."
RETRIEVE_CART_ERROR_CODE = 1001
RETRIEVE_CART_ERROR_TEXT = "Cart not found."
ADD_CART_ITEM_ERROR_CODE = 2000
ADD_CART_ITEM_ERROR_TEXT = "Failed to add item to cart."
DELETE_CART_ITEM_ERROR_CODE = 2001
DELETE_CART_ITEM_ERROR_TEXT = "Cart item doesn't exist."
AUTHORIZATION_ERROR_CODE = 3000
AUTHORIZATION_ERROR_TEXT = "Authorization failed."


RETRIEVE_CART_ERROR = {"code": RETRIEVE_CART_ERROR_CODE, "message": RETRIEVE_CART_ERROR_TEXT}
ACTIVE_CART_ALREADY_EXISTS_ERROR = {
    "code": ACTIVE_CART_ALREADY_EXISTS_ERROR_CODE,
    "message": ACTIVE_CART_ALREADY_EXISTS_ERROR_TEXT,
}
ADD_CART_ITEM_ERROR = {"code": ADD_CART_ITEM_ERROR_CODE, "message": ADD_CART_ITEM_ERROR_TEXT}
DELETE_CART_ITEM_ERROR = {
    "code": DELETE_CART_ITEM_ERROR_CODE,
    "message": DELETE_CART_ITEM_ERROR_TEXT,
}
AUTHORIZATION_ERROR = {
    "code": AUTHORIZATION_ERROR_CODE,
    "message": AUTHORIZATION_ERROR_TEXT,
}
