ACTIVE_CART_ALREADY_EXISTS_ERROR_CODE = 1000
ACTIVE_CART_ALREADY_EXISTS_ERROR_TEXT = "Active cart already exists."
RETRIEVE_CART_ERROR_CODE = 1001
RETRIEVE_CART_ERROR_TEXT = "Cart not found."
DELETE_CART_ERROR_CODE = 1002
DELETE_CART_ERROR_TEXT = "The cart can't be deactivated."
CART_OPERATION_FORBIDDEN_CODE = 1003
CART_OPERATION_FORBIDDEN_TEXT = "The cart can't be modified."
ADD_CART_ITEM_ERROR_CODE = 2000
ADD_CART_ITEM_ERROR_TEXT = "Failed to add item to cart."
ADD_CART_ITEM_MAX_QTY_ERROR_CODE = 2001
ADD_CART_ITEM_MAX_QTY_ERROR_TEXT = (
    "Failed to add item to cart. Max cart items qty limit exceeded."
)
UPDATE_CART_ITEM_MAX_QTY_ERROR_CODE = 2001
UPDATE_CART_ITEM_MAX_QTY_ERROR_TEXT = (
    "Failed to update cart item. Max cart items qty limit exceeded."
)
UPDATE_CART_ITEM_ERROR_CODE = 2002
UPDATE_CART_ITEM_ERROR_TEXT = "Failed to update cart item."
DELETE_CART_ITEM_ERROR_CODE = 2003
DELETE_CART_ITEM_ERROR_TEXT = "Cart item doesn't exist."
AUTHORIZATION_ERROR_CODE = 3000
AUTHORIZATION_ERROR_TEXT = "Authorization failed."
FORBIDDEN_ERROR_CODE = 3001
FORBIDDEN_ERROR_TEXT = "Forbidden."


RETRIEVE_CART_ERROR = {
    "code": RETRIEVE_CART_ERROR_CODE,
    "message": RETRIEVE_CART_ERROR_TEXT,
}
ACTIVE_CART_ALREADY_EXISTS_ERROR = {
    "code": ACTIVE_CART_ALREADY_EXISTS_ERROR_CODE,
    "message": ACTIVE_CART_ALREADY_EXISTS_ERROR_TEXT,
}
DELETE_CART_ERROR = {"code": DELETE_CART_ERROR_CODE, "message": DELETE_CART_ERROR_TEXT}
CART_OPERATION_FORBIDDEN = {
    "code": CART_OPERATION_FORBIDDEN_CODE,
    "message": CART_OPERATION_FORBIDDEN_TEXT,
}
ADD_CART_ITEM_ERROR = {
    "code": ADD_CART_ITEM_ERROR_CODE,
    "message": ADD_CART_ITEM_ERROR_TEXT,
}
ADD_CART_ITEM_MAX_QTY_ERROR = {
    "code": ADD_CART_ITEM_MAX_QTY_ERROR_CODE,
    "message": ADD_CART_ITEM_MAX_QTY_ERROR_TEXT,
}
UPDATE_CART_ITEM_ERROR = {
    "code": UPDATE_CART_ITEM_ERROR_CODE,
    "message": UPDATE_CART_ITEM_ERROR_TEXT,
}
UPDATE_CART_ITEM_MAX_QTY_ERROR = {
    "code": UPDATE_CART_ITEM_MAX_QTY_ERROR_CODE,
    "message": UPDATE_CART_ITEM_MAX_QTY_ERROR_TEXT,
}
DELETE_CART_ITEM_ERROR = {
    "code": DELETE_CART_ITEM_ERROR_CODE,
    "message": DELETE_CART_ITEM_ERROR_TEXT,
}
AUTHORIZATION_ERROR = {
    "code": AUTHORIZATION_ERROR_CODE,
    "message": AUTHORIZATION_ERROR_TEXT,
}
FORBIDDEN_ERROR = {"code": FORBIDDEN_ERROR_CODE, "message": FORBIDDEN_ERROR_TEXT}
