"""cart_config_data_migration

Revision ID: a5832f2bdde8
Revises: c666e7443c8d
Create Date: 2023-12-29 01:12:26.551220

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5832f2bdde8"
down_revision: Union[str, None] = "c666e7443c8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        INSERT INTO content.cart_config (data) VALUES 
        ('{"max_items_qty": 15, "min_cost_for_checkout": 500, "limit_items_by_id": {"1": 10, "2": 5, "3": 3}, "hours_since_update_until_abandoned": 12, "hours_since_update_until_abandoned": 12, "max_abandoned_notifications_qty": 3, "abandoned_cart_text": "Hello! Just a reminder: you have items in your app cart waiting for you. Come back and turn them into an order today!"}')
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cart_config",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cart_config",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        schema="content",
    )
    # ### end Alembic commands ###
