"""cart_notifications_table

Revision ID: f82269e25cac
Revises: a5832f2bdde8
Create Date: 2023-12-29 22:36:06.900189

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f82269e25cac"
down_revision: Union[str, None] = "a5832f2bdde8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart_notifications",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ABANDONED_CART", name="cart_notification_type_enum"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["content.carts.id"],
            name="cart_notifications_cart_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "cart_id"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_notifications", schema="content")
    # ### end Alembic commands ###

    sa.Enum(name="cart_notification_type_enum").drop(op.get_bind(), checkfirst=False)
