"""initial

Revision ID: bf7c0a17a582
Revises: 
Create Date: 2023-12-18 21:18:31.943798

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf7c0a17a582"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA content")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPENED", "DEACTIVATED", "LOCKED", "COMPLETED", name="cart_status_enum"
            ),
            server_default="OPENED",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    op.create_index(
        "idx_user_id_opened_status_unique",
        "carts",
        ["user_id", "status"],
        unique=True,
        schema="content",
        postgresql_where=sa.text("status = 'OPENED'"),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_weight", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["content.carts.id"],
            name="item_cart_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "cart_id"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_items", schema="content")
    op.drop_index(
        "idx_user_id_opened_status_unique",
        table_name="carts",
        schema="content",
        postgresql_where=sa.text("status = 'OPENED'"),
    )
    op.drop_table("carts", schema="content")
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA content")
