"""cart_is_active_field

Revision ID: 06ed45edb094
Revises: 5342dc3ec04f
Create Date: 2023-12-14 22:07:05.816411

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06ed45edb094"
down_revision: Union[str, None] = "5342dc3ec04f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("carts", sa.Column("is_active", sa.Boolean(), nullable=False), schema="content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("carts", "is_active", schema="content")
    # ### end Alembic commands ###
